version: '3'

services:
  sadApi:
    image: my_sad_api
    container_name: todoApi
    build: ./src 
    ports: 
    - "8080:8080"
    depends_on:
      - db
    env_file:
      - src/.env
    environment: 
      POSTGRES_HOST: db
  
  db:
    image: postgres:latest
    env_file:
      - src/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data: